config/routes.rb
Rails.application.routes.draw do
  root "steps#connect"
  resources :authentications
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/connect' => "steps#connect"

  get '/learn' => "steps#learn"

  get '/actions' => "steps#actions"

  get '/resources' => "steps#resources"

  get 'sites/jed'
  get 'sites/upworthy'
  get 'sites/nami'
  get 'sites/jed/:id' => "sites#jed", as: "jedclicked"

  get "/slides" => "slides#show"

end

app/models/depressed.rb
class Depressed < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.save!
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
	  @current_user ||= User.find_by uid: session[:uid] if session[:uid]
	end

	helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.from_omniauth(env["omniauth.auth"])
		session[:uid] = user.uid
		redirect_to jedclicked_path("clicked")
	end

	def destroy
		session[:uid]=nil
		redirect_to connect_path
	end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def jed
  	render layout: false
  end

  def upworthy
  	render layout: false
  end

  def nami
  	render layout: false
  end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  def show
  	render layout: false
    # @lesson = Lesson.find_by(lesson_number: params[:lesson_number])
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
	before_filter :set_depressed

  def connect
    # @graph = Koala::Facebook::API.new(current_user.oauth_token) unless current_user.nil?
    # raise unless current_user.nil?
  end

  def learn
  end

  def actions
  end

  def resources
  end

  private

  def set_depressed
    @depressed = Depressed.last
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
	def nav_link(link_text, link_path)
  class_name = current_page?(link_path) ? 'active' : ''

  content_tag(:li, :class => class_name) do
    link_to link_text, link_path
  end
end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrightDay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "header" %>

	<div class="container" >
		<%= yield %>
	</div>

	<%= render "footer" %>


</body>
</html>

app/views/sites/_widget.html.erb
<style type="text/css">

.sites-widget{
    padding:2em;
    background-color:#bbc8d0;
    color:#1a6ca4 !important;
}
.sites-widget h2{
 color: #1a6ca4 !important;
    margin-bottom: 15px !important;
}
.sites-widget p{
    color: #46677e;
}
.facebook-login{
  text-align: center;
  margin-top: 20px;
  margin-bottom: 20px;
}
.facebook-login a, .special-links a{
  background: #46677e;
  color: #fff;
  padding: 10px 20px;
  -webkit-font-smoothing: antialiased;
}
.facebook-login a:hover{
  background: #728b9c;
  text-decoration: none;
}
</style>
<div class="sites-widget">
	<h2>Depression is Closer to Home Than You Think</h2>
	<p>40 million adults are affected by major depression. It can be tough to wrap your head around such a large number, so click to connect with Facebook and we will put it in perspective.</p>
  <div class="facebook-login">
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  </div>
  <small style="float:right; color:white;">Powered by <span style="color:#1a6ca4 !important;">BrightDay</span></small>
</div>




<script>
(function() {
  jQuery(function() {
    $('body').prepend('<div id="fb-root"></div>');
    return $.ajax({
      url: "" + window.location.protocol + "//connect.facebook.net/en_US/all.js",
      dataType: 'script',
      cache: true
    });
  });

  window.fbAsyncInit = function() {
    FB.init({
      appId: '731526133562929',
      cookie: true
    });
    $('#sign_in').click(function(e) {
      e.preventDefault();
      return FB.login(function(response) {
        if (response.authResponse) {
          return window.location = '/auth/facebook/callback';
        }
      });
    });
    return $('#sign_out').click(function(e) {
      FB.getLoginStatus(function(response) {
        if (response.authResponse) {
          return FB.logout();
        }
      });
      return true;
    });
  };

}).call(this);

</script>

app/views/sites/_widget_second.html.erb
<style type="text/css">

.sites-widget{
    padding:2em;
    background-color:#bbc8d0;
    color:#1a6ca4 !important;
}
.sites-widget h2{
 color: #1a6ca4 !important;
    margin-bottom: 15px !important;
}
.sites-widget p{
    color: #46677e;
}
.facebook-login{
  text-align: center;
  margin-top: 20px;
  margin-bottom: 20px;
}
.facebook-login a, .special-links a{
  background: #46677e;
  color: #fff;
  padding: 10px 20px;
  -webkit-font-smoothing: antialiased;
}
.facebook-login a:hover{
  background: #728b9c;
  text-decoration: none;
}
</style>

<div class="sites-widget">
	<h2>Depression is Closer to Home Than You Think</h2>
	<p>Based on your 568 Facebook friends, depression statistics suggest that:</p>
	<ul style="font-size:1.2em; margin-bottom:30px;">
		<li><span style="font-weight:bold;">102 friends</span> will face major depression in their lifetime</li>
		<li><span style="font-weight:bold;">17 friends</span> are currently battling major depression</li>
	</ul>
	<div style="text-align:center; margin-top:10px;" class="special-links">
		<a href="/learn">I have been feeling down lately</a><br><br><br>
		<a href="/connect">I fear someone I care about may be depressed</a>
	</div>
	<div style="clear:both;">.</div>
<div style="text-align:right;">
  <small style="color:white;">Powered by <span style="color:#1a6ca4 !important;">BrightDay</span></small>
</div>
</div>

app/views/slides/show.html.erb
Show controller
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

<div class="reveal">
    <div class="slides">
        <section>Single Horizontal Slide</section>
        <section>
            <section>Vertical Slide 1</section>
            <section>Vertical Slide 2</section>
        </section>
    </div>
</div>

<script>
Reveal.initialize({

    // Display controls in the bottom right corner
    controls: true,

    // Display a presentation progress bar
    progress: true,

    // Display the page number of the current slide
    slideNumber: false,

    // Push each slide change to the browser history
    history: false,

    // Enable keyboard shortcuts for navigation
    keyboard: true,

    // Enable the slide overview mode
    overview: true,

    // Vertical centering of slides
    center: true,

    // Enables touch navigation on devices with touch input
    touch: true,

    // Loop the presentation
    loop: false,

    // Change the presentation direction to be RTL
    rtl: false,

    // Turns fragments on and off globally
    fragments: true,

    // Flags if the presentation is running in an embedded mode,
    // i.e. contained within a limited portion of the screen
    embedded: false,

    // Number of milliseconds between automatically proceeding to the
    // next slide, disabled when set to 0, this value can be overwritten
    // by using a data-autoslide attribute on your slides
    autoSlide: 0,

    // Stop auto-sliding after user input
    autoSlideStoppable: true,

    // Enable slide navigation via mouse wheel
    mouseWheel: false,

    // Hides the address bar on mobile devices
    hideAddressBar: true,

    // Opens links in an iframe preview overlay
    previewLinks: false,

    // Transition style
    transition: 'default', // default/cube/page/concave/zoom/linear/fade/none

    // Transition speed
    transitionSpeed: 'default', // default/fast/slow

    // Transition style for full page slide backgrounds
    backgroundTransition: 'default', // default/none/slide/concave/convex/zoom

    // Number of slides away from the current that are visible
    viewDistance: 3,

    // Parallax background image
    parallaxBackgroundImage: '', // e.g. "'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'"

    // Parallax background size
    parallaxBackgroundSize: '' // CSS syntax, e.g. "2100px 900px"


});
</script>

app/views/steps/_footer.html.erb
<div class="footer">
    <%=link_to( image_tag('jedlogo.gif'), sites_jed_path, :style => "margin-right:10px;") %>
    <%=link_to( image_tag('namilogo.jpg'), sites_nami_path) %>
</div>

app/views/steps/_header.html.erb
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand pull-right" href="/">BrightDay</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <%= nav_link 'Connect', connect_path %>
          <%= nav_link 'Learn', learn_path %>
          <%= nav_link 'Actions', actions_path %>
          <%= nav_link 'Resources', resources_path %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/steps/actions.html.erb
<div class="col-xs-12">
	<h1>Ideas to Brighten <%= @depressed.first_name %>'s Day</h1>
</div>
<div class="actions-options col-xs-12">
	<div class="messages">
		<h2>Send Her a Thoughtful Message</h2>
		<span class="glyphicon glyphicon-chevron-down"></span>
		<div class="action-content">
			<form class="form-horizontal">
				<div class="form-group  col-xs-12">
					<label class="col-xs-12 form-label">To: <%= @depressed.first_name %></label>
					<div class="col-xs-12">
						<textarea class="form-control" type="text" placeholder="Type your Facebook message here"></textarea>
					</div>
				</div>
				<div class=" col-xs-12">
					<button class="col-xs-11 btn btn-primary" style="margin-bottom: 20px">Send</button>
				</div>
			</form>
		</div>
		<div class="clearfix"></div>
	</div>

<div class="message-family">
		<h2>Share Your Concern With A Loved One</h2>
		<span class="glyphicon glyphicon-chevron-down"></span>
		<div class="action-content">
			<form class="form-horizontal">
				<div class="form-group  col-xs-12">
					<label class="col-xs-12 form-label">
						To: <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Select from <%= @depressed.first_name %>'s family members<span class="caret"></span></button>
					<ul class="dropdown-menu" role="menu">
					    <li><a href="#">Mom</a></li>
					    <li><a href="#">Dad</a></li>
					    <li><a href="#">Brother</a></li>
					</ul>
					</label>
					<div class="col-xs-12">
						<textarea class="form-control" type="text" placeholder="Type your message here"></textarea>
					</div>
				</div>
				<div class=" col-xs-12">
					<button class="col-xs-11 btn btn-primary" style="margin-bottom: 20px">Send</button>
				</div>
			</form>
			<div class="clearfix"></div>
		</div>
	</div>

	<div class="events">
		<h2>Plan an Event or Activity</h2>
		<span class="glyphicon glyphicon-chevron-down"></span>
		<div class="action-content">
			<p class="col-xs-12">We noticed that both Hannah and you are in New York City. Based on Hannah's interests, we found several upcoming activities that would be great to invite her to.</p>
			<div class="calendar-item col-xs-12">
				<div class="date col-xs-4">
					<p>Sept 21</p>
					<p>8:00pm</p>
				</div>
				<div class="event col-xs-8">
					<p>Ray Lamontagne Concert</p>
					<a href="#"><span class="glyphicon glyphicon-calendar"></span> Add to Calendar</a>
				</div>
			</div>
			<div class="calendar-item col-xs-12">
				<div class="date col-xs-4">
					<p>Sept 23</p>
					<p>10:00am</p>
				</div>
				<div class="event col-xs-8">
					<p>Women's Soccer Game</p>
					<a href="#"><span class="glyphicon glyphicon-calendar"></span> Add to Calendar</a>
				</div>
			</div>
			<div class="calendar-item col-xs-12">
				<div class="date col-xs-4">
					<p>Sept 26</p>
					<p>5:00am</p>
				</div>
				<div class="event col-xs-8">
					<p>Hiking Meetup: Poconos</p>
					<a href="#"><span class="glyphicon glyphicon-calendar"></span> Add to Calendar</a>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	<div class="products">
		<h2>Buy Her Something</h2>
		<span class="glyphicon glyphicon-chevron-down"></span>
		<div class="action-content">
			<p class="col-xs-12">We've selected products used to help treat depression. A UV lamp gives people some much-needed vitamin-D during the lonely winter months.</p>
			<%= image_tag("light.png", :alt => "Light",:class => "col-xs-12",:style => "max-width: 500px;") %>
			<%= image_tag("book.png", :alt => "Book",:class => "col-xs-12",:style => "max-width: 500px;") %>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="images">
		<h2>Send Upbeat Photos</h2>
		<span class="glyphicon glyphicon-chevron-down"></span>
		<div class="action-content">
			<p class="col-xs-12">Studies show pet photos can have a positive impact on someone's day. Select a cute puppy pic and send it to Hannah.</p>
			<%= image_tag("one_happy_puppy.jpg", :alt => "Puppy", :class => "col-xs-4") %>
			<%= image_tag("pp.jpeg", :alt => "Puppy 2", :class => "col-xs-4") %>
			<%= image_tag("pup.jpg", :alt => "Puppy 3", :class => "col-xs-4") %>
		</div>
		<div class="clearfix"></div>
	</div>


	<div class="reminders">
		<h2>Sign up for Future Tips and Reminders</h2>
		<span class="glyphicon glyphicon-chevron-down"></span>
		<div class="action-content">
			<p class="col-xs-12">Share your information so we can send more ideas so you can continue to help Hannah.</p>
			<form class="form-horizontal">
				<div class="form-group  col-xs-12">
					<label class="col-xs-12 form-label">Your Email</label>
					<div class="col-xs-12">
						<input class="form-control" type="text" placeholder="Email Address">
					</div>
				</div>
				<div class=" col-xs-12">
					<button class="col-xs-11 btn btn-primary" style="margin-bottom: 20px">Sign Up</button>
				</div>
			</form>
			<form class="form-horizontal">
				<div class="form-group  col-xs-12">
					<label class="col-xs-12 form-label">Phone Number</label>
					<div class="col-xs-12">
						<input class="form-control" type="text" placeholder="###-###-####">
					</div>
				</div>
				<div class=" col-xs-12">
					<button class="col-xs-11 btn btn-primary" style="margin-bottom: 20px">Sign Up</button>
				</div>
			</form>
		<div class="clearfix"></div>
		</div>
	</div>

</div>

<div class="next-step-container">
	<%= link_to "Next Step", resources_path, class: "next-step" %>
	<span class="glyphicon glyphicon-chevron-right"></span>
</div>

app/views/steps/connect.html.erb
<style>
/*
 *
 * Facebook Friend Autocomplete JQuery Plugin v0.0
 * https://agelber.github.com/facebook-friend-autocomplete
 *
 * Copyright 2014 Assaf Gelber
 * Released under the MIT license
 *
 */

.fbac-suggestion-list {
  font-family: 'lucida grande', tahoma, verdana, arial, sans-serif;
  font-size: 11px;
  font-weight: bold;
  font-color: #333;
  text-align: left;
  border: solid;
  border-width: 1px 1px 2px;
  border-color: #333 #333 #293e6a;
  padding: 2px 0px;
  z-index: 1000
}

.fbac-suggestion-list:empty {
  border: none;
}

.fbac-suggestion {
  padding: 2px 5px 2px 5px;
  background-color: #fff;
  border: 1px solid #fff;
  cursor: pointer;
}

.fbac-suggestion.fbac-selected {
  background-color: #6d84b4;
  border-color: #3b5998;
  color: #fff;
}

.fbac-suggestion-avatar {
  vertical-align: top;
}

.fbac-suggestion-name {
  margin-left: 20px;
  font-size:16px;
}
</style>

<h1>Brighten a Friend's Day</h1>
<p>BrightDay is a tool to help you learn about depression and discover ways to help those around you affected by it. All supportive actions you take are 100% private.</p>
</p>
<div id="login">
    <!-- <h2>Login in with Facebook to view the demo</h2>
    <p>Don't worry, we're not storing any data.</p> -->
    <button class="btn" id="fb-login">Login</button>
</div>
<div class="inner-addon right-addon">
    <i class="glyphicon glyphicon-search"></i>
		<input type="search" class="form-control" id="fb-input1" autofocus placeholder="Search your Facebook friends" />
</div>
<div class="next-step-container">
	<%= link_to "Next Step", learn_path, class: "next-step" %>
	<span class="glyphicon glyphicon-chevron-right"></span>
</div>

app/views/steps/learn.html.erb
<div class="col-xs-12">
	<h1>Concerned about <%= @depressed.first_name %>?</h1>
</div>
<form class="col-xs-12">
	<p>Has <%= @depressed.first_name %> shown any of these warning signs?</p>
	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">Expressed self-loathing
		</label>
	</div>
	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">Lack of interest in favorite things
		</label>
	</div>
	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">Stopped eating or binge eating
		</label>
	</div>
	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">Substance Abuse
		</label>
	</div>

	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">Suicidal comments
		</label>
	</div>
	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">Withdrawl
		</label>
	</div>

	<div class="col-xs-12">
		<div class="input-group">
			<span class="input-group-addon">
				<input placeholder="Other" type="checkbox">
			</span>
			<input type="text" class="form-control">
		</div><!-- /input-group -->
	</div><!-- /.col-lg-6 -->
</form>

<form class="col-xs-12">
	<p>Have any of these events recently happened to <%= @depressed.first_name %>?</p>
	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">Abuse or trauma
		</label>
	</div>
	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">Change in relationship status
		</label>
	</div>

	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">Moved homes
		</label>
	</div>
	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">New job/Lost job
		</label>
	</div>

	<div class="checkbox col-xs-12">
		<label>
		  <input type="checkbox">Not sure
		</label>
	</div>
	<div class="col-xs-12">
		<div class="input-group">
			<span class="input-group-addon">
				<input placeholder="Other" type="checkbox">
			</span>
			<input type="text" class="form-control">
		</div><!-- /input-group -->
	</div><!-- /.col-lg-6 -->
</form>
<div class="next-step-container">
	<%= link_to "Next Step", actions_path, class: "next-step" %>
	<span class="glyphicon glyphicon-chevron-right"></span>
</div>

app/views/steps/resources.html.erb
<h1>Resources</h1>
<p>Below are additional ways you can learn more about depression and help Hannah.</p>
<div class="resource-options col-xs-12">
	<h2>Suicide Hotline</h2>
	<p><a href="1-800-273-8255">1-800-273-8255</a>. Save this number to your phone contacts to ensure you have it for an emergency.</p>
	<button class="col-xs-12 btn btn-primary">Save to Phone</button>
	<h2>Educate yourself</h2>
	<p>Explore <a href="#" >Web MD</a> or <a href="#" >Mayo Clinic</a> for deeper analysis of depression symptoms and causes.</p>
	<button class="col-xs-12 btn btn-primary">Learn More</button>
	<h2>Doctors in Your Area</h2>
	<p>Find a phychologist or psychiatrist in your area.</p>
	<button class="col-xs-12 btn btn-primary">Find a Doctor Recommendation</button>
</div>

<div class="next-step-container">
	<%= link_to "Return to Home", connect_path, class: "next-step" %>
	<span class="glyphicon glyphicon-chevron-right"></span>
</div>